### ISSUE TITLE
Keyboard shortcuts not working for self compiled Cockatrice in Ubuntu

### ISSUE THREAD

**Issue by JanSvoboda** [Cockatrice/Cockatrice#476]
Hello,
I have compiled Cockatrice from source as is written on Cockatrice main page. When I run cockatrice, keyboard shortcuts are not working at all.

Combinations with CTRL + and even without CTRL (eg F3) are doing nothing.

My OS is Ubuntu 14.04.1
Cockatrice version is ef8bd60

I compiled Cocktrice with -DCMAKE_BUILD_TYPE=Debug, and tried to see if there will be some error message written in terminal regarding keyboard being pressed, but nothing was reported.

What should I provide for you?

BR
Jan

**Comment by viniciushana** [comment]
Wanted to let you all know that I had the very same issue and running cmake with -DWITH_QT4=1 fixed the keyboard shortcuts to me.

**Comment by skwerlman** [comment]
I am using QT5 on xubuntu 14.10, no issues here.

**Comment by tooomm** [comment]
We had some shortcut related issues with translations. If you used another language except the source language (english) they might be broken. We fixed that.

**Comment by pviollier** [comment]
Hi viniciushana, the same is happening to me. How can I follow your steps and cmake with " -DWITH_QT4=1"? Do I have to uninstall cockatrice? How is that done? (sorry, I'm new at this).

**Comment by viniciushana** [comment]
@pviollier No problem, you just have to rerun `make` passing `-DWITH_QT4=1` as one of the arguments and `make install` afterwards.

**Comment by pviollier** [comment]
Rerun means I should do all these steps again?

$ mkdir build   # create directory where complied files will go
$ cd build      # go to that directory
$ cmake ..      # run cmake
$ make          # compile
$ make install  # install

How exactly should I add "-DWITH_QT4=1" as an argument?

I tried doing:  "$ cmake .. -DWITH_QT4=1" but it didn't work.

**Comment by ZeldaZach** [comment]
`cmake .. -DWITH_QT4=1` is what you should do

**Comment by pviollier** [comment]
This is the error I get :(

pablo@pablo-EP45-UD3L:~/Cockatrice/build$ cmake .. -DWITH_QT4=1
-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Git: /usr/bin/git (found version "1.9.1") 
-- Performing Test CXX_HAS_WARNING_-Wcast-align
-- Performing Test CXX_HAS_WARNING_-Wcast-align - Success
-- Performing Test CXX_HAS_WARNING_-Wmissing-declarations
-- Performing Test CXX_HAS_WARNING_-Wmissing-declarations - Success
-- Performing Test CXX_HAS_WARNING_-Wno-long-long
-- Performing Test CXX_HAS_WARNING_-Wno-long-long - Success
-- Performing Test CXX_HAS_WARNING_-Wno-error=extra
-- Performing Test CXX_HAS_WARNING_-Wno-error=extra - Success
-- Performing Test CXX_HAS_WARNING_-Wno-error=delete-non-virtual-dtor
-- Performing Test CXX_HAS_WARNING_-Wno-error=delete-non-virtual-dtor - Success
-- Performing Test CXX_HAS_WARNING_-Wno-error=sign-compare
-- Performing Test CXX_HAS_WARNING_-Wno-error=sign-compare - Success
-- Performing Test CXX_HAS_WARNING_-Wno-error=missing-declarations
-- Performing Test CXX_HAS_WARNING_-Wno-error=missing-declarations - Success
UPDATE TRANSLATIONS: OFF
-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - not found
-- Found Qt4: /usr/bin/qmake-qt4 (found suitable version "4.8.6", minimum required is "4.8.0") 
-- Found Qt 4.8.6
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found PROTOBUF: /usr/lib/x86_64-linux-gnu/libprotobuf.so  
-- Found Qt4: /usr/bin/qmake-qt4 (found version "4.8.6") 
-- Using QtMobility version: system's default
Qt QTMULTIMEDIA library not found.
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pablo/Cockatrice/build

**Comment by Daenyth** [comment]
That's doesn't look like an error. Continue with `make`

**Comment by pviollier** [comment]
Ok, so I continued with "make", and then "make install" and I got this error (the same as last time)

pablo@pablo-EP45-UD3L:~/Cockatrice/build$ make install
[  1%] Automoc for target cockatrice_common
[  1%] Built target cockatrice_common_automoc
[  1%] Automoc for target cockatrice_protocol
[  1%] Built target cockatrice_protocol_automoc
[ 65%] Built target cockatrice_protocol
[ 69%] Built target cockatrice_common
[ 69%] Automoc for target cockatrice
[ 69%] Built target cockatrice_automoc
[ 93%] Built target cockatrice
[ 94%] Automoc for target oracle
[ 94%] Built target oracle_automoc
[100%] Built target oracle
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/bin/cockatrice
CMake Error at cockatrice/cmake_install.cmake:42 (FILE):
  file INSTALL cannot copy file
  "/home/pablo/Cockatrice/build/cockatrice/cockatrice" to
  "/usr/local/bin/cockatrice".
Call Stack (most recent call first):
  cmake_install.cmake:38 (INCLUDE)


make: *** [install] Error 1
pablo@pablo-EP45-UD3L:~/Cockatrice/build$

**Comment by ctrlaltca** [comment]
Ubuntu lesson #1: ```sudo make install```

**Comment by pviollier** [comment]
This is the log for when I runned "make"

http://pastebin.com/TV8zZFyE

**Comment by pviollier** [comment]
Oohh, lol, sorry guys. I feel really ashamed. With Sudo it worked

**Comment by ZeldaZach** [comment]
I'll assume this issue is fixed then? If so, can you close :)

**Comment by ctrlaltca** [comment]
No need to feel ashamed, in reality it should be up to us to to provide some easy to use prebuilt package. Some work has been done in #491 , but it seems that nobody really likes to pick it up when it comes to debian packaging.

**Comment by pviollier** [comment]
Now it works like a charm :)

**Comment by Mr-Yann** [comment]
Small update that might help other people : 
I encountered the same problem (non functioning short-cuts) on Linux Ubuntu Mate 15.10 (up to date on 01/2016)
So I tried the -DWITH_QT4=1 and got various fatal errors about either ZLIB not found or LIBGCRYPT non found.

These problems were solved by temporarily renaming my anaconda3 folder, only for the duration of the build process.

Some custom short-cuts still behave strangely, but this is another story (ctrl+V for example seems impossible to assign to something else, but there is no warning)

Anaconda3 is a python3 distribution that switches default python to python3. So, my guess is that the actual build process somewhere relies on a python script that is not compatible with anaconda3 python distribution and does not check those dependencies thoroughly enough.

**Comment by ctrlaltca** [comment]
> So, my guess is that the actual build process somewhere relies on a python script that is not compatible with anaconda3 python distribution and does not check those dependencies thoroughly enough.

We don't use python anywhere, so i'm confused here.

Did you try checking if you have a package named ```appmenu-qt5``` installed and removing it? This should solve the problems when using Qt5.

**Comment by Mr-Yann** [comment]
I just double-checked : I re-compiled the game with qt5 and without 
appmenu-qt5 installed.
With that game, I start a local game : before using chat box, ctrl+U 
untaps all, after using chat box ctrl+U (as an example) does not work 
anymore.

Concerning python, I was able to reproduce the problem :
in directory /build i type rm -r * (because i was not sure if the 
previous config would be overwritten or not)
then cmake .. -DWITH_QT4=1
and it gets me :

CMake Warning at oracle/CMakeLists.txt:132 (ADD_EXECUTABLE):
  Cannot generate a safe runtime search path for target oracle because 
files
  in some directories may conflict with libraries in implicit 
directories:

    runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be 
hidden by files in:
      /home/yann/anaconda3/lib

  Some of these libraries may not be found correctly.




If i don't remove all files in build, so keeping thoose created from 
the QT5 version, i don't get this error (that is fatal to the make 
package process).
Note that rm -r * followed only by cmake .. (no error) and cmake .. 
-DWITH_QT4=1 gets the same error. I need to compile the whole package 
with qt5 to be able tu run cmake .. without the aforementioned error.

But if I rename anaconda3 during the cmake, I don't get the error.

I'm no expert but can gladly provide any info or log that might help 
you, if interested.
_____
Yann


Le mar. 2 févr. 2016 à 18:17, ctrlaltca <notifications@github.com> a 
écrit :

**Comment by ctrlaltca** [comment]
> With that game, I start a local game : before using chat box, ctrl+U
> untaps all, after using chat box ctrl+U (as an example) does not work
> anymore.

Yep, this is a known problem of "focus stealing". Clicking on the game area (like, on a card) will restore the focus to the game and make shortcuts working again. We'll eventually fix this on a future release when a reliable method is found.

> Cannot generate a safe runtime search path for target oracle because
> files in some directories may conflict with libraries in implicit directories:
> runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu
> may be hidden by files in:
> /home/yann/anaconda3/lib

So, it seems that anaconda is in your $PATH and is overriding some libraries already shipped with your operating system. When cmake (our build system) tries to look for a specific library named zlib, if finds the one bundled with anaconda and misses the correct one (the one shipped with the operating system).
This problem can be avoided temporarily renaming the anaconda folder as you did.
A more complex solution could be to remove anaconda from getting added automatically to your $PATH and loading it manually when you need to use it.
I suppose you did something like this: http://docs.continuum.io/anaconda/faq#on-os-x-or-linux-what-causes-a-conda-command-not-found-error to add it (or the package installer did it itself).

**Comment by Mr-Yann** [comment]
I guess you are right. The package installer certainly did it, and it 
is fine by me since my python3 works well. It is however strange that 
this zlib override is not causing problem for QT5 cmake and also not 
causing problem for QT4 cmake after a QT5 make package.

On a side note, after testing with the QT5 version, the problem seems 
different than what you say : even if I click on a card to reset focus, 
ctrl+U does not work anymore. So I stay with QT4 version for the moment.

_____
Yann


Le mar. 2 févr. 2016 à 19:19, ctrlaltca <notifications@github.com> a 
écrit :

**Comment by Copitox** [comment]
Hi everyone. I'm having the same issue. Followed the instructions here and shortcuts are still not working. I realized when I run `cmake .. -DWITH_QT4=1` it returns 

CMake Warning:
  Manually-specified variables were not used by the project:

    WITH_QT4

This is the complete cmake output

`$ cmake .. -DWITH_QT4=1
-- The C compiler identification is GNU 5.3.1
-- The CXX compiler identification is GNU 5.3.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.7.4") 
-- Performing Test CXX_HAS_WARNING_-Wcast-align
-- Performing Test CXX_HAS_WARNING_-Wcast-align - Success
-- Performing Test CXX_HAS_WARNING_-Wmissing-declarations
-- Performing Test CXX_HAS_WARNING_-Wmissing-declarations - Success
-- Performing Test CXX_HAS_WARNING_-Wno-long-long
-- Performing Test CXX_HAS_WARNING_-Wno-long-long - Success
-- Performing Test CXX_HAS_WARNING_-Wno-error=extra
-- Performing Test CXX_HAS_WARNING_-Wno-error=extra - Success
-- Performing Test CXX_HAS_WARNING_-Wno-error=delete-non-virtual-dtor
-- Performing Test CXX_HAS_WARNING_-Wno-error=delete-non-virtual-dtor - Success
-- Performing Test CXX_HAS_WARNING_-Wno-error=sign-compare
-- Performing Test CXX_HAS_WARNING_-Wno-error=sign-compare - Success
-- Performing Test CXX_HAS_WARNING_-Wno-error=missing-declarations
-- Performing Test CXX_HAS_WARNING_-Wno-error=missing-declarations - Success
-- UPDATE TRANSLATIONS: OFF
-- Found Qt 5.5.1
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    WITH_QT4


-- Build files have been written to: /home/copitox/Cockatrice/Cockatrice/build

'
edit: Sorry, I can't seem to get "code" insert properly.

**Comment by Copitox** [comment]
I'm getting the following error on `cmake .. -DWITH_QT4=1`

Manually-specified variables were not used by the project:

    WITH_QT4


So it's not compiling with QT4, and therefore shortcuts are still not working. How do I fix it?

**Comment by Copitox** [comment]
Apparently there is no -DWITH_QT4=1 flag now. This is from the README

> The following flags can be passed to `cmake`:
>
>- `-DWITH_SERVER=1` Whether to build the server (default 0 = no).
>- `-DWITH_CLIENT=0` Whether to build the client (default 1 = yes).
>- `-DWITH_ORACLE=0` Whether to build oracle (default 1 = yes).
>- `-DPORTABLE=1` Build portable versions of client & oracle (default 0 = no).
>- `-DCMAKE_BUILD_TYPE=Debug` Compile in debug mode. Enables extra logging output
>, debug symbols, and much more verbose compiler warnings (default `Release`).
>- `-DUPDATE_TRANSLATIONS=1` Configure `make` to update the translation .ts files
> for new strings in the source code. Note: Running `make clean` will remove the 
>.ts files (default 0 = no).
>- `-DTEST=1` Enable regression tests (default 0 = no). Note: needs googletest, w
>ill be downloaded on the fly if unavailable. To run tests: ```make test```.

**Comment by ctrlaltca** [comment]
@Copitox: Qt4 support has been removed recently in the development version in https://github.com/Cockatrice/Cockatrice/pull/1979. It's still present in the last stable version.

**Comment by Daenyth** [comment]
We need to configure more information on system setup because the qt5 version works for most people. There's got to be some environmental difference

**Comment by Copitox** [comment]
I installed [this prepackaged binary](http://www.magic-league.com/zach/cockatrice_bin.php?os=UNIX_DEV) and still can't use keyboard shortcuts. So maybe the issue is not with the compiling process?

**Comment by ZeldaZach** [comment]
The binary you installed was made for Ubuntu 14, not 16. There may be different requirements in the versions

**Comment by Copitox** [comment]
Shoot. Could someone running Ubuntu 16.04 compile and send me a .deb, please? I can't think of a way to fix this issue, or workaround it.

**Comment by ctrlaltca** [comment]
The original issue was reported for Ubuntu 14, where a known problem exists when running qt5 apps when the appmenu-qt5 package is installed.
A few weeks ago i've tested compiling on ubuntu 16 + qt5 + appmenu-qt5, and everything was working fine.
Do you have the appmenu-qt5 package installed?

**Comment by Copitox** [comment]
Yes, appmenu-qt5 was installed all along. Just to be clear, I did manage to compile using qt5, it's just that keyboard shortcuts don't work.

`$ sudo apt-get install appmenu-qt5
Reading package lists... Done
Building dependency tree       
Reading state information... Done
appmenu-qt5 is already the newest version (0.3.0+16.04.20151130-0ubuntu1).
appmenu-qt5 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`

**Comment by Daenyth** [comment]
Using `git checkout fffc3e7e0089ded84d4c6cbdbd38cef36e25fdb0` will let you still build the qt4 version for now, but you won't be able to update from there if this is a blocker.

Can you include any other information about your system? Are you using a non-english locale? Anything that would distinguish it from a normal install? What DE+WM? Any system hotkey program running that could possibly intercept things?

**Comment by Copitox** [comment]
Nothing out of the ordinary. Fresh Ubuntu 16.04 with the latest updates, english language. 

Using checkout let me use the qt4 flag on cmake, but before I could compile I had to manually install [qtmobility-dev](https://launchpad.net/ubuntu/xenial/amd64/qtmobility-dev/1.2.0-3ubuntu5) and resolve a lot of its dependencies (also manually) for it. Apparently all those requiered packages are obsolete now, acording to Launchpad.

Currently compiling, will update when finished.

**Comment by Daenyth** [comment]
What sort of hardware are you on? Laptop? Model? I'm at a loss for why it doesn't work. I am finding hints from google that this is a qt5 issue, so it might be related to a specific version of that.

**Comment by Daenyth** [comment]
I found this issue for `texmaker` which has the same problem: https://code.google.com/archive/p/texmaker/issues/1301

> The QT5 packages in ubuntu 14.10 are still patched for unity and buggy : all the Qt standard shortcuts behavior is broken (just compile Qt5 by yourself and you will see that there is no problem)

So this could be that

**Comment by Daenyth** [comment]
@Copitox If you uninstall `appmenu-qt5` does it work?

**Comment by Daenyth** [comment]
https://bugs.launchpad.net/appmenu-qt5/+bug/1380702

**Comment by Copitox** [comment]
@Daenyth I've already got it up and working. I don't know if i'm knowledgeable enough to fix it if I screw up again.

I plan on setting up a VM as soon as posible  and see if I can replicate the issue to keep troubleshooting.

**Comment by Daenyth** [comment]
Thanks. Note that while the qt4 version will for you for now you won't be
able to upgrade until this is resolved, and eventually there's going to
come some new feature that requires you to use an update to connect to an
updated server

**Comment by Copitox** [comment]
@Daenyth Just tested it. I set up a fresh Ubuntu 16.04 install on VirtualBox. I updated, upgraded, installed all the requiered stuff.

I first compiled with appmenu-qt5 uninstalled. Keyboard shortcuts worked fine. Then I reinstalled appmenu-qt5 and recompiled. Keyboard shortcuts did NOT work.

So, that seems to be the issue.

If you need any more info to debug just tell me what and how and i'll update here.

**Comment by Daenyth** [comment]
At the bottom of the thread on that launchpad ticket I linked to there's a
command using env to be used with app menu installed. Can you try that? If
they works we have a workaround that doesn't require people to uninstall
the package, though I'm fine with having them uninstall it

**Comment by Copitox** [comment]
Cockatrice compiled with appmenu-qt5 installed -> Keyboard shortcuts don't work.

Installed texmaker (it was like a 800MB download btw), ran it with
env UBUNTU_MENUPROXY= texmaker
Didn't make a difference. Shortcuts still don't work.

**Comment by quotidianophidian** [comment]
On a 16.04 laptop with the same issues here. I read through everything here, but I would appreciate a note explaining exactly which of these many interrelated solutions is the current workaround. As it stands, I can't tell how much of the steps I need to replicate to get the program working again.

**Comment by tooomm** [comment]
@quotidianophidian did you try https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#menus-are-not-visible-on-ubuntu-1404-when-not-using-unity ?

**Comment by quotidianophidian** [comment]
That does indeed fix it. However, given that I had tried this same fix before and it failed. I did recompile the program between now and then, which might have made the difference, since I first compiled it a few months ago.

**Comment by tooomm** [comment]
Can we close this since we have it in the wiki and the huge amount of comments here is more consing than helping?

**Comment by TMiguelT** [comment]
Oddly, I just build the package with and without `appmenu-qt5` (using `sudo apt install  appmenu-qt5`) on Ubuntu 16.10, and it the shortcuts work fine in both cases. This might be because of an update to the Qt version in 16.10 (mine says `Qt 5.6.1`). Can anyone else confirm this?

**Comment by francescocadei** [comment]
Ubuntu 16.10
QMake version 3.0
Using Qt version 5.6.1 in /usr/lib/x86_64-linux-gnu

But shortcuts don't work in both cases (with and without appmenu-qt5 (using sudo apt install appmenu-qt5))

**Comment by ctrlaltca** [comment]
This is supposed to be fixed on recent Ubuntu package versions (see: https://bugs.launchpad.net/appmenu-qt5/+bug/1380702).
